package cmd

import (
	"fmt"
	"gauth/auth"

	"github.com/spf13/cobra"
)

var VerifyJwt = &cobra.Command{
	Use:              "verify",
	Short:            "Verifies JWT generated by login",
	TraverseChildren: true,
	Run: func(cmd *cobra.Command, args []string) {
		tokenString := TOKEN
		if isAuth := auth.ValidateJWT(tokenString); isAuth {
			fmt.Println("your mom gay lmao")
		} else {
			fmt.Println("Invalid Token")
		}

	},
}
